name: Commit lint

on:
  workflow_call:
  pull_request:

jobs:
  commitlint-tengf:
      runs-on: ubuntu-24.04
      steps:
        - name: Print Hello
          run: |
            echo "Commitlint is working! Host: $(hostname)"